[tool.poetry]
name = "django-projects"
version = "0.1.1"
description = "Django Projects for Learning"
authors = ["Udhay Prakash Pethakamsetty <uday3prakash@gmail.com>"]
license = "Apache"
readme = "README.md"
packages = [{include = "django_projects"}]

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1.2.3"
requests = "^2.34.2"
pandas = "^2.3.3"
django = "4.2.27"
djangorestframework = "^3.17.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
