# Generated by Django 2.1 on 2020-03-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='target_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='action',
            field=models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('archived', 'archived')], default='created', max_length=8),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
