# Generated by Django 3.0.4 on 2020-03-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_auto_20200331_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='date_of_birth',
            new_name='date_of_contact',
        ),
    ]
