# Generated by Django 3.0.4 on 2020-03-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_auto_20200331_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='date_of_contact',
            field=models.DateField(),
        ),
    ]
